# ---------------------------------------------------------------
# Author Information
# ---------------------------------------------------------------
author:
  name: 王锦乐
  nick: 好好编程

# ---------------------------------------------------------------
# Social Settings
# ---------------------------------------------------------------
# Social Links.
# Usage: `Key: permalink | title | font icon`
social:
  GitHub: https://github.com/qw8880000 | github
  E-Mail: mailto:qw8880000@126.com | envelope
