# ---------------------------------------------------------------
# Author Information
# ---------------------------------------------------------------
author:
  name: 王锦乐
  nick: 好好编程

# ---------------------------------------------------------------
# Social Settings
# ---------------------------------------------------------------
# Social Links.
social:
  - type: link
    title: Github
    link: https://github.com/qw8880000
    icon:
  - type: email
    title: E-Mail
    link: qw8880000@126.com
    icon:
